### ISSUE TITLE
Bug:  Crystal Ready Marker counts as 10

### ISSUE THREAD

**Issue by laasker** [azerothcore/mod-arena-3v3-solo-queue#2]
### Current Behaviour

Hey, i understand this module is still in early stages but i will post some bugs and features that i have in mind if that's okay.

So, i tested the module and noticed i got in a 1v1 arena, but when the module is finished it will be a 3v3, and the crystal that reduces the starting time needs 10 people to click on it(like its an 5v5), instead of 6 (an 3v3), this way when all 6 players are ready, the crystal will reduce the starting time.

Here's the code for the readymarker:
https://github.com/azerothcore/azerothcore-wotlk/blob/482f4c94ffdb9cd859482d977aa31a18a60ef8d9/src/server/game/Battlegrounds/Battleground.cpp#L1302

### Expected Behaviour

It should need only 6 people to click on the crystal, instead of 10. 

### Steps to reproduce the problem

1. Queue Solo queue arena with 2 characters
2. Enter arena with atleast one of them
3. Click on the red crystal before the arena begins, it will say "You are marked as ready 1/10"

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e0bc7d73ddaae154dc113bbfa83390ffbb3040fb

### Operating system

Windows 10 x64

**Comment by pangolp** [comment]
Hello, thanks for the report, there are many things to change or improve. In fact, I was looking at the 1v1 module, and I thought that it could easily be adapted to achieve a 3v3. However, I have not had results, but the thing about the crystals is due to a configuration issue. I have accommodated that, however, what worries me the most is the fact that the queue is executed, with 1 person on each team. And since I haven't been able to solve that, or actually, I have been able to, but not in the way I would have liked, then I didn't move forward in other aspects.

**Comment by laasker** [comment]
> Hello, thanks for the report, there are many things to change or improve. In fact, I was looking at the 1v1 module, and I thought that it could easily be adapted to achieve a 3v3. However, I have not had results, but the thing about the crystals is due to a configuration issue. I have accommodated that, however, what worries me the most is the fact that the queue is executed, with 1 person on each team. And since I haven't been able to solve that, or actually, I have been able to, but not in the way I would have liked, then I didn't move forward in other aspects.

If you need help with testing let me know, i'm 'laasker' on the azerothcore discord

**Comment by pangolp** [comment]
> If you need help with testing let me know, i'm 'laasker' on the azerothcore discord

Perfect, thanks. Now I am going to upload a change related to this topic. I accommodated the glass issue and the type issue, however, there is still a lot to do, because the queue continues to call, even though the team is not complete and there are only 2 people. I leave you the pull request so you can try it, and tell me if you have the same results as me.
